id: P000515
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18130
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པའི་ཚིག་ལེའུར་བྱས་པ།
  author: ''
  volumes:
    54118ce48cb14432a9ffe024e11f89ef:
      image_group_id: I8LS19965
      title: Volume 1 of theg pa chen po mdo sde'i rgyan zhes bya ba'i tshig le'ur
        byas pa/
      volume_number: 1
      total_pages: 296
ebook_metadata:
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པའི་ཚིག་ལེའུར་བྱས་པ།
  author: ''
  sku: P000515
  cover: cover.jpg
  layers:
  - pagination
